DECLARE
  v_sessionUser        VARCHAR2(30);
  v_sessionId          VARCHAR2(30);
  v_ipAddress          VARCHAR2(30);
  v_language           VARCHAR2(30);
  v_osUser             VARCHAR2(30);
  v_terminal           VARCHAR2(30);
  v_host               VARCHAR2(30);
  v_bgJobId            VARCHAR2(30);
  v_module             VARCHAR2(30);
  v_action             VARCHAR2(30);
  v_clientIdentifier   VARCHAR2(30);
  v_currentUser        VARCHAR2(30);
  v_dbName             VARCHAR2(30);
  v_serverHost         VARCHAR2(30);
  v_nlsTerritory       VARCHAR2(30);
  v_sid                VARCHAR2(30);
  v_currentSchema      VARCHAR2(30);
  v_currentEditionName VARCHAR2(30);
  v_instanceName       VARCHAR2(30);
BEGIN
  v_sessionUser        := SYS_CONTEXT('USERENV', 'SESSION_USER');
  v_sessionId          := SYS_CONTEXT('USERENV', 'SESSIONID');
  v_ipAddress          := SYS_CONTEXT('USERENV', 'IP_ADDRESS');
  v_language           := SYS_CONTEXT('USERENV', 'LANGUAGE');
  v_osUser             := SYS_CONTEXT('USERENV', 'OS_USER');
  v_terminal           := SYS_CONTEXT('USERENV', 'TERMINAL');
  v_host               := SYS_CONTEXT('USERENV', 'HOST');
  v_bgJobId            := SYS_CONTEXT('USERENV', 'BG_JOB_ID');
  v_module             := SYS_CONTEXT('USERENV', 'MODULE');
  v_action             := SYS_CONTEXT('USERENV', 'ACTION');
  v_clientIdentifier   := SYS_CONTEXT('USERENV', 'CLIENT_IDENTIFIER');
  v_dbName             := SYS_CONTEXT('USERENV', 'DB_NAME');
  v_currentUser        := sys_context('USERENV', 'CURRENT_USER');
  v_serverHost         := sys_context('USERENV', 'SERVER_HOST');
  v_nlsTerritory       := sys_context('USERENV', 'NLS_TERRITORY');
  v_sid                := sys_context('USERENV', 'SID');
  v_currentSchema      := sys_context('userenv', 'CURRENT_SCHEMA');
  v_currentEditionName := SYS_CONTEXT('userenv', 'CURRENT_EDITION_NAME');
  v_instanceName       := SYS_CONTEXT('USERENV', 'INSTANCE_NAME', 200);

  DBMS_OUTPUT.PUT_LINE('Session User         : ' || v_sessionUser);
  DBMS_OUTPUT.PUT_LINE('Session ID           : ' || v_sessionId);
  DBMS_OUTPUT.PUT_LINE('IP Address           : ' || v_ipAddress);
  DBMS_OUTPUT.PUT_LINE('Language             : ' || v_language);
  DBMS_OUTPUT.PUT_LINE('OS User              : ' || v_osUser);
  DBMS_OUTPUT.PUT_LINE('Terminal             : ' || v_terminal);
  DBMS_OUTPUT.PUT_LINE('Host                 : ' || v_host);
  DBMS_OUTPUT.PUT_LINE('Background Job ID    : ' || v_bgJobId);
  DBMS_OUTPUT.PUT_LINE('Module               : ' || v_module);
  DBMS_OUTPUT.PUT_LINE('Action               : ' || v_action);
  DBMS_OUTPUT.PUT_LINE('Client Identifier    : ' || v_clientIdentifier);
  DBMS_OUTPUT.PUT_LINE('Database Name        : ' || v_dbName);
  DBMS_OUTPUT.PUT_LINE('Server Host          : ' || v_serverHost);
  DBMS_OUTPUT.PUT_LINE('Nls Territory        : ' || v_nlsTerritory);
  DBMS_OUTPUT.PUT_LINE('Sid                  : ' || v_sid);
  DBMS_OUTPUT.PUT_LINE('Current Schema       : ' || v_currentSchema);
  DBMS_OUTPUT.PUT_LINE('Current Edition Name : ' || v_currentEditionName);
  DBMS_OUTPUT.PUT_LINE('InstanceName         : ' || v_instanceName);
END;
/